owner: d4khosting 
repo: uptime-crwdp-ca 

sites:
  - name: CRWDP Website
    url: https://www.crwdp.ca
  - name: D4K Hosting Server
    url: https://vps.d4kservers.net
    slug: d4k-hosting-server
    icon: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon.svg

status-website:
  cname: crwdp.d4kstatus.net
  favicon: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon-192x192.png
  faviconSvg: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon.svg
  logoUrl: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-logo-2023.svg
  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: preconnect
      href: https://fonts.gstatic.com
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap
    - rel: stylesheet
      href: https://d4khosting.github.io/uptime-assets/css/d4k-status.css
  name: CRWDP Uptime Status
  introTitle: "**Uptime Status for CRWDP Website**"
  introMessage: Real-time status and historical uptime records for the CRWDP website and the D4K Web Hosting Server. If the CRWDP website is down while the D4K Web Hosting Server is up, please log in to your Control Panel and review your files and settings before contacting D4K Hosting. If both sites are down, then check the [D4K Hosting Status](https://www.d4kstatus.net/) page for updates.
  metaTags:
    - name: "robots"
      content: "noindex"
